### ISSUE TITLE
start-mongodb Github Action: MongoDB 6.0 and 7.0 not working on ubuntu2404

### ISSUE THREAD

**Issue by johnnyshields** [mongodb-labs/drivers-evergreen-tools#652]
I'm aware this is not "officially supported", but as a heads-up, when I run the following config in Github Actions:

```
      - id: start-mongodb
        name: start mongodb
        uses: mongodb-labs/drivers-evergreen-tools@master
        with:
          version: "7.0"
          topology: "replica_set"

causes:

ValueError: No download was found for version="7.0" target="ubuntu2404" arch="x86_64" edition="enterprise" component="archive"
```

Version "8.0" works without issue on ubuntu2404.
